version: 2
jobs:
  build-server:
    working_directory: ~/meditrinae-server
    docker:
      - image: circleci/node:11.10.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "server/package.json" }}
            - v1-dependendies-
      - run:
          name: install-dependencies
          command: cd server && npm install
      - save_cache:
          paths:
            - server/node_modules
          key: v1-dependencies-{{ checksum "server/package.json" }}
      - run:
          name: build-server
          command: cd server && npm run build
  deploy-staging:
    docker:
      - image: circleci/node:11.10.0
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "./deploy_meditrinae_staging.sh"

workflows:
  version: 2
  build-and-deploy-if-staging:
    jobs:
      - build-server
      - deploy-staging:
          filters:
            branches:
              only:
                - staging
          requires:
            - build-server
