#
# This is a hello world HOT template just defining a single compute
# server.
#
heat_template_version: 2013-05-23

description: >
  Template used to deploy simple python web server on one container for INF8480 class.

parameters:
  flavor:
    type: string
    description: Flavor for the server to be created
    default: INF4410-mini
    constraints:
      - custom_constraint: nova.flavor
  image:
    type: string
    description: Image ID or image name to use for the server
    default: INF4410-Ubuntu-trusty-mini
    constraints:
      - custom_constraint: glance.image
  network_id:
    type: string
    default: inf4410-net

resources:
  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks: 
        - network: {get_param: network_id}
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            wget https://raw.githubusercontent.com/houssemmh/INF8480-TP3/master/server.py
            python server.py &
          params:
            $param: param

outputs:
  server_networks:
    description: The networks of the deployed server
    value: { get_attr: [server, networks] }
